Update README.md
zenika-open-source/awesome-remote-work pull request #14
Opened 2020-10-01 17:17 UTC by CallMeGoodWater

New article of Simon Sinek on working on remote

2020-10-01 20:51 UTC, zigarn requested changes

2020-10-01 20:51 UTC, zigarn commented on README.md
> +- [Maintain connection with your team while working remote by Simon Sinek ](https://simonsinek.com/commit/huddle-how-to/)
```suggestion
- [Maintain connection with your team while working remote by Simon Sinek](https://simonsinek.com/commit/huddle-how-to/)
```

2020-10-02 09:13 UTC, merged

2020-10-02 09:14 UTC, jlandure commented
@all-contributors please add @CallMeGoodWater for doc

2020-10-02 09:17 UTC, jlandure commented
@all-contributors please add @zigarn for review