:memo: Add material that I use
zenika-open-source/awesome-remote-work pull request #62
Opened 2021-01-14 09:30 UTC by emeric-martineau

2021-01-14 15:12 UTC, lucsorel requested changes

2021-01-14 15:12 UTC, lucsorel commented on awesome-remote-equipment-fr.md
> +> « Jabra est très réputé pour ses casques audio et vous allez vite comprendre pourquoi. Très confortable, simple à utiliser, de bonne qualité. Seul le réglage de la courbure du micro est un peu dure
"pour être confortable pendant les réunions" : la syntaxe suggère le sens "pour que vous soyez confortable". Ce n'est pas un usage correct de "confortable" qui s'applique à un objet ou une situation, mais pas à des personnes (sauf quand une personne est installée dans/sur une autre...). Reformulations proposées, selon le sens voulu :

1. "mais c'est le minimum pour être à l'aise pendant les réunions qui peuvent durer 2h"
2. "mais c'est le minimum pour avoir un micro-casque confortable pendant les réunions qui peuvent durer 2h" (je ne crois pas que c'était ce sens qui était recherché)

2021-01-14 15:19 UTC, emeric-martineau commented on awesome-remote-equipment-fr.md
> +> « Jabra est très réputé pour ses casques audio et vous allez vite comprendre pourquoi. Très confortable, simple à utiliser, de bonne qualité. Seul le réglage de la courbure du micro est un peu dure
Merci de la suggestion 👍

2021-01-14 17:12 UTC, JuliaLehoux reviewed
I'm not enough confident to merge the new elements in Julien's part so I let him review it.

2021-01-18 10:25 UTC, jlandure requested changes

2021-01-18 10:25 UTC, jlandure commented on README.md
> +[![All Contributors](https://img.shields.io/badge/all_contributors-20-orange.svg?style=flat-square)](#contributors-)
Hey @emeric-martineau please remove this modification. It will be added with all-contributor bot. 👍

2021-01-18 10:39 UTC, jlandure commented on README.md
> +[![All Contributors](https://img.shields.io/badge/all_contributors-20-orange.svg?style=flat-square)](#contributors-)
I've edited your file. 👍

2021-01-18 10:39 UTC, merged

2021-01-18 10:40 UTC, jlandure commented
@all-contributors please add @emeric-martineau for doc