:sparkles: Add chair Corsair T3 rush
zenika-open-source/awesome-remote-work pull request #71
Opened 2021-01-28 17:18 UTC by RouxAntoine

Advice about Corsair T3 rush after one year of use.

2021-01-28 17:41 UTC, jlandure requested changes

2021-01-28 17:41 UTC, jlandure commented on awesome-remote-equipment-fr.md
> +> « Je l'ai depuis un an bien en été car la matière ne tient pas trop chaud. Niveau confort c'est pas mal mais un peut trop droit. Point plus l'inclinaison 180° pour les siestes le midi 👌 »
```suggestion
> « Je l'ai depuis un an bien en été car la matière ne tient pas trop chaud. Niveau confort c'est pas mal mais un peu trop droit. Point en plus: l'inclinaison 180° pour les siestes le midi 👌 »
```

2021-01-28 17:44 UTC, jlandure approved these changes

2021-01-28 17:44 UTC, merged

2021-01-28 17:45 UTC, jlandure commented
@all-contributors please add @RouxAntoine for doc

2021-01-28 17:47 UTC, RouxAntoine commented on awesome-remote-equipment-fr.md
> +> « Je l'ai depuis un an bien en été car la matière ne tient pas trop chaud. Niveau confort c'est pas mal mais un peut trop droit. Point plus l'inclinaison 180° pour les siestes le midi 👌 »
Merci 👌

2021-01-29 08:26 UTC, jlandure commented on awesome-remote-equipment-fr.md
> +> « Je l'ai depuis un an bien en été car la matière ne tient pas trop chaud. Niveau confort c'est pas mal mais un peut trop droit. Point plus l'inclinaison 180° pour les siestes le midi 👌 »
De rien ! 🙌